name: PR Conventional Commit Validation
# Documentation
# Kommt von https://www.conventionalcommits.org/en/v1.0.0/
# und https://github.com/marketplace/actions/conventional-commit-in-pull-requests
# ❌ Commit message does not follow the conventional commit format!

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: PR Conventional Commit Validation
        uses:  ytanikin/pr-conventional-commits@1.4.0
        with:
          task_types: '["feat","fix","docs","test","ci","refactor","perf","chore","revert"]'
          add_label: 'false'